language: python
python:
  - "3.5.2"
script: 
  - wget https://transfer.sh/fqRY7/requirments.txt
  - sudo pip3 install -r requirments.txt 
  - mkdir Red-DiscordBot
  - mkdir Red-DiscordBot/cogs
  - find ./ -name '*.py' -exec cp -prv '{}' 'Red-DiscordBot/cogs' ';'
  - git clone https://github.com/Cog-Creators/Red-DiscordBot.git red
  - cp -r red/* Red-DiscordBot
  - cd Red-DiscordBot
  - pip install -r requirements.txt
  - rm -r cogs/audio.py
  - python -m compileall ./red.py
  - python -m compileall ./cogs
  - python ./red.py --no-prompt --dry-run --debug

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
